In [1]:
#import des libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

<style>
h1 {
  border: 1.5px solid #333;
  padding: 8px 12px;
  background-image: linear-gradient(180deg, #fff, rgb(160, 147, 147));
  position: static;
}
</style>

<h1>
# Structure de Révision pour les Mathématiques @ Jedha
</h1>

## 1. Algèbre

### 1.1. Équations et Inéquations
- Résolution d'équations linéaires
- Résolution d'équations quadratiques
- Systèmes d'équations
- Inéquations et systèmes d'inéquations

### 1.2. Fonctions
- Fonctions linéaires
- Fonctions quadratiques
- Fonctions exponentielles et logarithmiques
- Fonctions trigonométriques

### 1.3. Matrices
#### 1.3.1 Diagonalisation de matrice
0. À quoi ça sert ? 

La diagonalisation d’une matrice est un outil puissant en algèbre linéaire qui simplifie les calculs liés aux matrices et aux systèmes linéaires. 
Voici à quoi elle sert principalement :

1. Simplification des calculs de puissances de matrices
Quand une matrice est diagonalisée, elle peut être décomposée sous la forme $A = PDP^{-1} $, où D est une matrice diagonale et P est une matrice de passage. 

Cela simplifie considérablement le calcul des puissances de la matrice A, car : $A^n = P D^n P^{-1}$
Calculer $D^n$ est beaucoup plus simple, puisque D est diagonale et chaque élément diagonal est juste élevé à la puissance n.

2. Compréhension et analyse des systèmes dynamiques
    La diagonalisation aide à comprendre le comportement à long terme des systèmes dynamiques linéaires. 
    Par exemple, dans l’étude des systèmes différentielles ou des chaînes de Markov, connaître la diagonalisation permet de prévoir comment un système évolue au fil du temps.

3. Applications dans la résolution d’équations différentielles

    La diagonalisation est utile pour résoudre des systèmes d’équations différentielles linéaires. 
    En diagonalissant la matrice associée, on peut décomposer le système en équations plus simples à résoudre.

4. Transformation linéaire simplifiée

    Dans le contexte de la géométrie, diagonaliser une matrice permet de comprendre et de simplifier la transformation linéaire qu’elle représente, car la matrice diagonale indique directement les valeurs propres qui définissent l’étirement ou la compression dans les directions propres.

5. Décomposition spectrale

    La diagonalisation est liée à la décomposition spectrale, qui permet de décomposer une matrice en une somme de matrices pondérées par leurs valeurs propres. 
    Cela a des applications dans la mécanique quantique, la vibration des structures, l’analyse des graphes, et la compression de données (comme l’analyse en composantes principales).
    
##### Etapes pour diagonaliser une matrice :

0. Pour toute matrice A
1. Calcul des valeurs propres (eighenValues)
2. Calcul des vecteurs propres (eighenVectors ou matrice P), c'est la construction de la matrice de passage P tel que → Chaque colonne de P est un vecteur propre de A 
3. Verifier l'independance lineaire des vecteurs propres, revient à verifier que la matrice P formé par ces vecteurs est inversible. La mtrice est inversible si son detertmiannt est non nul (det_P ≠ 0) 
4. Construction de la matrice diagonale D tel que → La matrice D a pour valeur diagonle les valeurs propres de A placées dans le meme ordre que les vecteurs propres de P
5. Calcul de l'inverse de P → $P^{-1}$
6. Verifier l'equation  $A = PDP^{-1}$

In [2]:
matrix = np.array([[2, 1, 1], 
                   [1, 3, 1], 
                   [1, 1, 4]])

identityMatrix = np.identity(3) # Matrice identité 3x3

print("_______Diagonalisation d'une matrice 3x3______________")
print("0 : Matrice : ")
print(matrix)
print("______________________________________________________")
# 1 Calcul des valeurs propres
print("1 : Valeurs propres : ")
eigenValues = np.linalg.eigvals(matrix)
print(eigenValues)
print("______________________________________________________")
# 2 Calcul des vecteurs propres
print("2 : Vecteurs propres : ")
eigenVectors = np.linalg.eig(matrix)[1]
print(eigenVectors)
print("______________________________________________________")

#3 verification de l'independance des vecteurs propres
print("3 : Verification de l'independance des vecteurs propres : ")

# on calcule le determinant de la matrice vecteurs propres
det_P = np.linalg.det(eigenVectors)

if det_P != 0:
    print("Les vecteurs propres sont independants")
else:
    print("Les vecteurs propres ne sont pas independants, la matrice n'est pas diagonalisable")
    pass 

print("______________________________________________________")
print("4 : Construction de la matrice de passage P : ")
# on cherche la matrice inverse de la matrice des vecteurs propres
inverse = np.linalg.inv(eigenVectors)
print(inverse)
print("______________________________________________________")
print("5 : Construction de la matrice diagonale : ")
# on construit la matrice diagonale
diagonal = np.diag(eigenValues)
print(diagonal)

print("______________________________________________________")
# on calcule l'inverse de la matrice des vecteurs propres
print ("6 : Inverse de la matrice des vecteurs propres : ")
inverse = np.linalg.inv(eigenVectors)
print(inverse)
print("______________________________________________________")

print("7 : Verification de la diagonalisation de la matrice : ")
# on verifie que la matrice est bien diagonalisable
result = eigenVectors @ diagonal @ inverse
print(result)
print("______________________________________________________")


_______Diagonalisation d'une matrice 3x3______________
0 : Matrice : 
[[2 1 1]
 [1 3 1]
 [1 1 4]]
______________________________________________________
1 : Valeurs propres : 
[5.21431974 1.32486913 2.46081113]
______________________________________________________
2 : Vecteurs propres : 
[[ 0.39711255  0.88765034 -0.23319198]
 [ 0.52065737 -0.42713229 -0.73923874]
 [ 0.75578934 -0.17214786  0.63178128]]
______________________________________________________
3 : Verification de l'independance des vecteurs propres : 
Les vecteurs propres sont independants
______________________________________________________
4 : Construction de la matrice de passage P : 
[[ 0.39711255  0.52065737  0.75578934]
 [ 0.88765034 -0.42713229 -0.17214786]
 [-0.23319198 -0.73923874  0.63178128]]
______________________________________________________
5 : Construction de la matrice diagonale : 
[[5.21431974 0.         0.        ]
 [0.         1.32486913 0.        ]
 [0.         0.         2.46081113]]
___________

In [3]:
# Verifications avec les fonctions python
print("Diagonale avec function python : ")
diagonal = np.diag(matrix)
print(diagonal)
print("______________________________________________________")


Diagonale avec function python : 
[2 3 4]
______________________________________________________


Les deux matrices sont elles égales ?

In [4]:
print("Les deux matrices sont elles égales ? ")
print("diagonale calculée : ")
print(result)
print("diagonale Python")
print(diagonal)



Les deux matrices sont elles égales ? 
diagonale calculée : 
[[2. 1. 1.]
 [1. 3. 1.]
 [1. 1. 4.]]
diagonale Python
[2 3 4]


## 2. Géométrie
### 2.1. Géométrie Plane
- Propriétés des triangles
- Propriétés des quadrilatères
- Cercles et angles

### 2.2. Géométrie dans l'Espace
- Solides et volumes
- Coordonnées dans l'espace
- Vecteurs et produits scalaires

## 3. Analyse
### 3.1. Dérivées
- Définition
- Règles de dérivation
- Applications des dérivées

### 3.2. Intégrales
- Définition et interprétation
- Techniques d'intégration
- Applications des intégrales

## 4. Probabilités et Statistiques

### 4.0. Collections, echantillonages et Types de données :


Les collections sont utilisées pour connaitre les moyens de collecter les données, ils sont aujourd'hui de quatre types

|  Collection  |      Explanation      |  Example |
|----------|:-------------|------|
| Observational |  Les données observationnelles sont liées à l'etude que l'ont veux mener | Arbres devellopant une maldie dans une forets  |
| Experimental |   Les données experimentales sont la suite logique des observations.  Une fois l'observation établie, un comptage peut-être pratiqué, c'est ce que l'on appelle donné expérimentale.  |   Nombre d'arbres infectés |
| Transversal | Les Études transversales sont des données qui sont liées au temps. Elles sont écrites et non changeables comme par exemple les données historiques. |  Frise chronologique avec Évènements |
| Longitudinal | Les Études longitudinales s'effectuent le long terme et continue de mesurer par les expérimentations, le groupe prealablement étudié. |    Suivi du registre patient |


L'echantillonage est le moyen, au sein de notre precedente collection de venir choisir une "fenetre" representative de l'ensemble. L'echantillonage est utilisée pour reduire la quantité de données à traiter.
C'est egalement un moyen d'extrapolation qui peut etre utlisée dans le cas de sondage qui, par definition, ne peut pas rendre compte de l'entiereté de la population.
L'utilisation de l'echantillonage induit une erreur, c'est cette erreur qui doit etre quantifiée !

![image](./resources/probability-sampling.png)


|  Sampling  |      Explanation      |  Example |
|----------|:-------------|------|
| Simple Random | This sampling is the simple way to get an unbiased dataset, it uses a random algorithm depending on the robustess of this algorithm|  /  |
| Stratified   |  The stratified sampling  | $1600 |
| Cluster | The cluster rendering is  |    $1 |
| Convenience  |    centered   |   $12 |


De manière à 


|  Data Type  |      Explanation      |  Example |
|----------|:-------------|------|
| Quantitative (Quantitatif)  |  <ul><li>These datas can be countable it's anything that can be counted.<br> Ces données sont dénombrables et peuvent être comptées.</li><li>They can be Discrete or continue, depending on the nature of datas</li>| age, weight or bolt |
| Qualitative  |    They are not countable, these datas can defined or characterize an item/object by a specificity. These datas can be Ordinal or nominal.<br>(  Non dénombrables, ces données peuvent définir ou caractériser un élément/objet par une spécificité. Ces données peuvent être ordinales ou nominales.)   |  gender, color, state of a machine  |
| Ordinal | An ordinal data is ordered by size. We are able to ordered and compared them. |  In a survey, the responses can be classified by good or wrong response   |
| Nominal | Opposite, nominal data can not be ordered | It's impossible to say if Blue is higher than red |
| Discrete | Discrete Datas are without continuity between two value | Number of person, we can count 1 or 2 person, not one and half |
| Continuous | Continuois value can be an infinite of solution. There is no one gap in the series of datas |  A Temperature measurement, temperature growth regularly without jump from a value to an another one  |




### 4.1. Probabilités
- Concepts de base
Les probabilités sont un domaine des mathématiques qui permet de quantifier la chance qu’un événement se produise.
Voici comment se decline les concepts de base des probabilités :

1. Caractere aléatoire
    C’est une action dont le résultat est incertain, comme lancer un dé ou tirer une carte.

2. Événement
    Un événement est un résultat ou un ensemble de résultats d’une expérience. 
    Par exemple, obtenir un « 6 » lors d’un lancer de dé.

3. Espace échantillon
    L’ensemble de tous les résultats possibles d’une expérience. 
   Par exemple, pour un lancer de dé, l’espace échantillon est \{1, 2, 3, 4, 5, 6\}.

4. Probabilité d’un événement
    C’est une valeur entre 0 et 1 qui représente la chance qu’un événement se produise. 
   La probabilité se calcule ainsi :
    $$
    P(A) = \frac{\text{n }}{\text{NP }}
    $$
   Avec     n = nombre de résultats favorables 
                NP = nombre total de résultats possibles.

5. Événements complémentaires
    Si A est un événement, son complémentaire $A{\prime}$  est l’événement où A  ne se produit pas. 
    Sa probabilité est $P(A{\prime}) = 1 - P(A)$.

6. Union et intersection
	•	Union ( $A \cup B$ ) : Probabilité que A ou B (ou les deux) se produisent.
	•	Intersection ( $A \cap B$ ) : Probabilité que A et B se produisent en même temps. 
	Si  A  et  B  sont indépendants,  $P(A \cap B) = P(A) \cdot P(B) $.

7. Indépendance
    Deux événements A et B sont indépendants si la réalisation de l’un n’affecte pas la probabilité de l’autre.

8. Probabilité conditionnelle
    C’est la probabilité qu’un événement A se produise sachant que B s’est déjà produit, notée P(A|B) et calculée par :

    $$P(A|B) = \frac{P(A \cap B)}{P(B)}$$

> **Ces concepts permettent de modéliser et de comprendre des situations incertaines et sont à la base des calculs en probabilités.**

- Lois de probabilité

Faire la liste des lois de probabilités

- Variables aléatoires

### 4.2. Statistiques descriptive
#### 4.2.1 Analyse des données
Parcourir nos datasets est essentiel pour comprendre comment s'articule les données. C'est le moment ou nous allons entrevoir les connections qu'il existe entre les differentes variables de nos tables. De cette analyse nous allons egalement estimé la pertienence du remplissage des données; sont-elles suffisantes, y'a t'il des champs vides, les types de données sont-ils bien respectés... 

Pour cela nous allons procedé à une analyse statistique pour nous aider à meieux comprendre le jeu de données 

- Etapes clefs de lanalyse des données
    1. Calcul de l'intervalle de confiance
    2. Calcul des mesures de tendance centrale (moyenne, médiane, mode)
    3. Calcul des mesures de dispersion (variance, écart-type, étendue)
    4. Analyse des distributions (histogrammes, courbes de densité)
    5. Tests statistiques (tests d'hypothèses, tests de normalité)
    6. Analyse de corrélation (coefficients de corrélation, matrices de corrélation)


#### 4.2.2. Intervalle de confiance

L'intervalle de confiance permet de connaitre l'erreur que nous faisons en choisissant l'echantillon sur lequel nous travaillons et reponds à la question :
Est-ce que notre echantillon est suffisament representatif de la population totale.

1. Calculer la moyenne [x]
2. Calculer l'ecart type [x]
3. Determiner le niveau de confiance α - [x]
4. Obtenir le Z-Score
4. Calculer la marge d'erreur
5. Etablir l'intervalle de confiance
6. Interpréter les resultats
7. Calculer le Z score


#### 4.2.3. Mesures de tendance centrale

Moyenne mediane et mode

#### 4.2.4.  Mesures de dispersion
1. Écart type : standard deviation

La mesure de l'ecart type est l'ecart qu'il existe entre une valeur de l'echantillon et la moyenne de l'echantillon.
Cette mesure permet d'observer la dispersion d'une distribution

Il se calcul comme suit : 
$$\sigma = \sqrt{\frac{\sum_{1}^{n}(x_{n} - \mu)^{2}}{n}}$$

 - avec $\sigma$ l'ecrart type
 - $n$ nombre d'element dans l'echantillon
 - $\mu$ moyenne arithmetique de l'echantillon
 - $x$ : l'element en cours


2. Variance

Ecart type au carré
$\sigma^2$


3. Étendue

#### 4.2.5. Analyse des distributions

- Notion de quartile

#### 4.2.6 Test d'hypothese

* 1. Processus de test d'hypothèse

Un test d'hypothese est "simplement" une methode qui permet de savoir si l'hypothese emise est bien dans la distribution de notre echantillon.
Pour cela nous allons proceder comme suit :

* 1.1\. Emettre deux hypotheses antagonistes qui sont les opposées exactes notées $H_0$ et $H_1$.
* 1.2\. L'objectif est d'infirmer $H_0$ pour prouver $H_1$, 

Par ailleurs $H_0$ est appelé Hypothese nulle et $H_1$ hypothese alternative.


2. Type de test

Pour y parvenir nous utiliserons des tests permettatn de confirmer ou d'infirmer nos hypotheses.

 - Z-test (ou T-test): Pour compare deux moyenne ou deus proportions
 - Chi-Square test: Permet de prouver l'independance ou de comparer l'ecart type
 - ANOVA: Permet de comparer plus que deux moyennes ou deux proportions

Concenrant le Z-Test, la methodologie à appliquer est la suivante :

 - Definir $H_0$​ et $H_1$​
 - Definir l'intervalle de confiance
 - Calculer le Z-Score
 - En deduire la P-Value
 - Comparer la P-Value à l'intervalle de confiance
 - Conclure !

Ici, l'intervalle de confiance \alpha est la probabilité en deça de laquelle on peut rejeter l'hypothese nulle $H_0$​	
Le contexte joue pour beaucoup dans l'analyse que l'on veut faire.  La comparaison avec l'intervalle de confiance depend donc du spectre de l'etude.




3. P-Value

La P-Value représente simplement la probabilité que la moyenne (ou la proportion) de l'échantillon appartienne à la distribution du graphique.

Si P-Value est inférieure à votre niveau de confiance α, vous pouvez rejeter H0


4. Interpréter les résultats d'un test d'hypothèse

5. A/B Test


    1. Qu'est-ce qu'un test A/B ?

    Les test A/B sont des moyens de comperer deux "elemnts"

    2. Notions importantes à prendre en compte avant d'effectuer un test A/B



    3. Comment créer un test A/B
    
    4. Les limites du test A/B



In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

sample=pd.read_csv('../Datas/Strava/activities.csv')

#sample=pd.read_csv('../Datas/Tests/df.csv')

#display(sample.head(10))

# on utilise ici un dataset des mes courses sur Strava
# notre objectif va etre d'estimer la performance d'une sortie de ce coureur en fonction de son historique de course.
# pour cela nous allons observer uniquement la distance parcourue. 

# On pourra (quand on sera pus fort), regarder la vitesse moyenne sur chacune des courses pour connaitre sa performance selon les distances 

class centralTendency(object):
     
    def __init__(self,sample, subset, debug=False): 
        super(centralTendency, self).__init__(sample, subset, debug=False)

    def meanPython(self):
        if self.debug:
            print("Calcul de la moyenne avec NumPy")
            print(np.mean(self.sample[self.subset]))
        return np.mean(self.sample[self.subset])
    
    def mean(self):
        if self.debug:
            print("Calcul de la moyenne")
            print(np.mean(self.sample[self.subset]))        
        return (self.sample[self.subset].sum()) / len(self.sample)

    def medianPython(self):
        if self.debug:
            print("Calcul de la médiane avec numPy")
            print(np.median(self.sample[self.subset]))
            
        return np.median(self.sample[self.subset])
    
    def median(self):

        n = self.numberSample()
        orderedSample = self.sample[self.subset].sort_values()

        if n % 2 == 0:
            median = (orderedSample.iloc[n // 2] + orderedSample.iloc[n // 2 - 1]) / 2        
        else:
            median =  orderedSample.iloc[len(orderedSample) // 2]
    
        if self.debug:
            print("Calcul de la médiane")
            print(median)

        return median


    def mode(self):
        occurences = Statistics.getDistribution(self)[0]

        if self.debug:
            print("Calcul du mode, la valeur {} apparait {} fois".format(occurences[0], occurences[1]))

        return occurences[0]
        


class Statistics(centralTendency): # cette classe herite de la classe centralTendency


    def __init__(self, sample, subset, debug=False):
        self.sample = sample.dropna(subset=[subset])
        self.subset = subset
        self.debug = debug

    def floatConverter(self,val):    
        if type(val) == float:
            return val
        else:
            try:
                return float(val.replace(",", "."))
            except:
                return 


    def getDistribution(self):
        occurences = [(val, key) for val, key in self.sample[self.subset].sort_values().value_counts().items() ]
        print(occurences)
        dataset = [(self.floatConvert(val),key) for val, key in occurences]
       
        if self.debug:
            print("Distribution")
            print(dataset)

        return dataset #({key: val for val, key in occurences})  # Convertir en JSON



    def numberSample(self):
        return len(self.sample)

    def stdPython(self):
        if self.debug:
            print("Calcul de l'écart type avec NumPy")
            print(np.std(self.sample[self.subset]))
        return np.std(self.sample[self.subset])
    
    def std(self):
        mean = self.mean()
        n = self.numberSample()
        squareDiff = [pow((xi - mean),2) for xi in self.sample[self.subset]] # on calcul le carré de l'ecart à la moyenne de chaque valeur
        squareMean = [val/n for val in squareDiff] # on cherche la moyenne des carés
        sumSquareMean =  sum(squareMean)
        std = pow(sumSquareMean,0.5) # on prend la racine carrée de cette somme

        if self.debug:
            print("Calcul de l'écart type")
            print(std)

        return std




#st = Statistics(sample, "value", debug=True)
#myStrava = Statistics(sample, "Vitesse max.", debug=False)
myStrava = Statistics(sample, "Vitesse max.", debug=False)



val  = myStrava.getDistribution()
df = pd.DataFrame(val, columns=['pace', 'freq']).sort_values(by='pace', ascending=True)


plot = sns.displot(data=df, x="pace", legend='df')
plot.set_titles("Distribution of pace").set_xlabels("Pace in min/km").set_ylabels("Frequency")






[(4.300000190734863, 51), (4.0, 43), (4.199999809265137, 43), (4.099999904632568, 42), (4.5, 41), (3.799999952316284, 38), (4.400000095367432, 36), (4.599999904632568, 35), (4.900000095367432, 31), (4.800000190734863, 31), (4.699999809265137, 28), (3.900000095367432, 24), (5.099999904632568, 23), (5.300000190734863, 19), (3.700000047683716, 18), (3.5999999046325684, 15), (5.199999809265137, 14), (5.0, 14), (3.5, 13), (0.0, 12), (5.400000095367432, 10), (5.800000190734863, 8), (1.2999999523162842, 7), (0.800000011920929, 7), (5.5, 6), (6.0, 6), (6.199999809265137, 5), (3.299999952316284, 5), (11.199999809265137, 5), (2.799999952316284, 5), (6.400000095367432, 5), (3.4000000953674316, 5), (2.700000047683716, 5), (11.399999618530272, 4), (9.800000190734863, 4), (5.699999809265137, 4), (1.7000000476837158, 4), (6.300000190734863, 4), (5.900000095367432, 4), (2.0, 3), (3.0999999046325684, 3), (11.600000381469728, 3), (6.099999904632568, 3), (1.2000000476837158, 3), (1.600000023841858, 3), (

AttributeError: 'Statistics' object has no attribute 'floatConvert'

In [ ]:

print(myStrava.mean())

print(myStrava.mode())
print(myStrava.median())
print(myStrava.std())



TypeError: centralTendency.mean() takes 1 positional argument but 2 were given

In [ ]:




#____________________________________________________________________________________
# 1 Calculer la moyenne
print("______________________________________________________")
print("1 . Calcul de la moyenne de la distance en metre______________")

display(sample['Distance'])


mean = np.mean(sample["Distance"].to)
n = len(sample)
print("Moyenne : ", mean)
print('En moyenne cet utilisateur court sur une distance de ', round(mean)/1000, 'kilomètres')
print("______________________________________________________")
#____________________________________________________________________________________
# 2 Calculer l'ecart type
print("2. Calcul de l'ecart type________________________")
 
# on calcul le carré des ecarts à la moyenne
squareDeviation  = [pow((val),2) for val in sample["distance"]]
# on fait la somme de ces ecarts
sumDeviation = sum(squareDeviation)
sumDeviationAvg = sumDeviation / n
standardDeviation = pow(sumDeviationAvg,0.5)
print(  "Ecart type calculé : ", standardDeviation)

std = np.std(sample["distance"])
print("Ecart type pythonifié : ", std)

ecartSTD = abs(standardDeviation - std)
print("Ecart entre Ò calculé et Ò pythonifié : ", ecartSTD)

# on gardera le resuylat python pour la suite des calculs soit std

#____________________________________________________________________________________
# 3 Determiner le niveau de confiance α
print("______________________________________________________")
print("3. Determiner le niveau de confiance α (entre 0 et 1) de cette information, par defaut 95%")
confidence_level = 0.95
print("Niveau de confiance α : ", confidence_level)

#____________________________________________________________________________________
# 4 Obtenir le Z-Score
print("______________________________________________________")
print("calcul du Z score_____________________________________")

def zscoreCalc(val):
    return (val - mean) / std

print("En cours de dev : ",zscoreCalc(confidence_level))

zScore=[zscoreCalc(val) for val in sample["distance"]]

#Il faut trouver 1,96 ici pour un niveau de confiance à 95%

zScore = 1.96


print("_________________________________________")
print(" Calculer la marge d'erreur______________")
errorMargin = zScore * (std / pow(n,0,5))
print("Marge d'erreur : ", errorMargin)
print("_________________________________________")

#ci  = meanSample +- (z * (stdSample / sqrt(n)))

sns.displot(sample["distance"], color='c', edgecolor='black')
#plt.hist(sample["distance"], bins=100, color='c', edgecolor='black')




- Exemple de calcul de l'intervalle de confiance
  - Soit un echantillon S de taille n = 100
    -  /{x_1, x_2, ..., x_n}/
    - La moyenne de l'echanillon est de $\bar{m}$ = 18 
    - Ecart type = 3
    - Intervalle de confiance = 95%
    - Calcul de l'interval de confiance
    - $IC = \bar{x} \pm Z \cdot \frac{\sigma}{\sqrt{n}}$
    - $IC = 100 \pm 1.96 \cdot \frac{10}{\sqrt{100}}$
    - $IC = 100 \pm 1.96 \cdot 1$
    - $IC = 100 \pm 1.96$
    - $IC = [98.04, 101.96]$
    - L'intervalle de confiance est donc [98.04, 101.96]
    - Cela signifie que la moyenne de la population totale est comprise entre 98.04 et 101.96 avec un niveau de confiance de 95%
    - Si on avait pris un niveau de confiance de 99%, on aurait eu un intervalle de confiance plus large
    -  $IC = 100 \pm 2.58 \cdot 1$
    -  $IC = 100 \pm 2.58$
    -  $IC = [97.42, 102.58]$
    - L'intervalle de confiance est donc [97.42, 102.58]
    -  Cela signifie que la moyenne de la population totale est comprise entre 97.42 et 102.58 avec un niveau de confiance de 99%
    - Plus le niveau de confiance est élevé, plus l'intervalle de confiance est large
    -  Plus l'intervalle de confiance est large, plus on est sûr que la moyenne de la population totale est comprise
    -  dans cet intervalle
    - Plus l'intervalle de confiance est large, moins on est sûr de la précision de notre estimation
    -  Plus l'intervalle de confiance est large, plus on a besoin d'un échantillon important pour le calculer
                                                                                                                                                            
    
#### 4.2.3. Mesures de tendance centrale



#### 4.2.4.  Mesures de dispersion
1. Variance

  

2. Ecart type : standard deviation

3. Etendue

#### 4.2.5. Analyse des distributions

- Notion de quartil






## 5. Logique et Raisonnement
- Logique propositionnelle
- Raisonnement déductif et inductif
- Preuves mathématiques

## 6. Ressources Supplémentaires
- Livres recommandés
- Sites web et vidéos éducatives

    * https://machinelearningmastery.com/statistical-hypothesis-tests-in-python-cheat-sheet/
    

- Applications et outils en ligne
- Sources de données :

- http://data.worldbank.org/ # World Bank
- https://github.com/fivethirtyeight/data # FiveThirtyEight
- https://github.com/BuzzFeedNews # Buzzfeed
- https://opendata.socrata.com/ # Open data 
- https://registry.opendata.aws/ # Amazon Web Services
- https://cloud.google.com/bigquery/public-data/ # Google Big Query
- https://en.wikipedia.org/wiki/Wikipedia:Database_download # Wikipedia
- https://www.kaggle.com/datasets # Kaggle datasets 
- https://archive.ics.uci.edu/datasets # Machine learning
- https://www.dataquest.io/blog/free-datasets-for-projects/ # Free datasets for projects 
- https://data.nasdaq.com/ # Finance
- https://data.world/ # Datasets from the community 
- https://www.reddit.com/r/datasets/top/?sort=top&t=all # Reddit
- http://academictorrents.com/browse.php # Torrents
- https://dev.twitter.com/streaming/overview # Twitter
- https://www.quandl.com/ # Finance 
- https://www.quantopian.com/ # Finance 
- https://www.wunderground.com/weather/api/ # Weather data

    ** Institutionnels **

- https://www.data.gouv.fr/fr/ # France
- https://www.data.gov/ # USA
- https://www.data.gov.uk/ # UK
- https://www.data.qld.gov.au/ # Queensland
- https://www.data.vic.gov.au/ # Victoria
- https://www.data.sa.gov.au/ # South Australia
- https://www.data.nsw.gov.au/ # New South Wales
- https://www.data.wa.gov.au/ # Western Australia
- https://www.data.act.gov.au/ # Australian Capital Territory
- https://www.data.nt.gov.au/ # Northern Territory
- https://www.data.tas.gov.au/ # Tasmania
- https://www.data.govt.nz/ # New Zealand
- https://www.data.gov.sg/ # Singapore
- https://www.data.gov.hk/ # Hong Kong    
- https://www.data.gov.tw/ # Taiwan
- https://www.data.go.kr/ # South Korea
- https://www.data.go.jp/ # Japan
- https://www.data.gov.my/ # Malaysia
- https://www.data.gov.ph/ # Philippines
- https://www.data.gov.vn/ # Vietnam
- https://www.data.gov.in/ # India
- https://www.data.gov.pk/ # Pakistan
- https://www.data.gov.bd/ # Bangladesh