In [15]:
#import de libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Structure de Révision pour les Mathématiques @ Jedha


## 1. Algèbre

### 1.1. Équations et Inéquations
- Résolution d'équations linéaires
- Résolution d'équations quadratiques
- Systèmes d'équations
- Inéquations et systèmes d'inéquations

### 1.2. Fonctions
- Fonctions linéaires
- Fonctions quadratiques
- Fonctions exponentielles et logarithmiques
- Fonctions trigonométriques

### 1.3. Matrices
#### 1.3.1 Diagonalisation de matrice
A quoi ca sert ? 

La diagonalisation d’une matrice est un outil puissant en algèbre linéaire qui simplifie les calculs liés aux matrices et aux systèmes linéaires. 
Voici à quoi elle sert principalement :

1. Simplification des calculs de puissances de matrices
Quand une matrice est diagonalisée, elle peut être décomposée sous la forme  A = PDP^{-1} , où  D  est une matrice diagonale et  P  est une matrice de passage. 

Cela simplifie considérablement le calcul des puissances de la matrice  A , car : A^n = P D^n P^{-1}
Calculer  D^n  est beaucoup plus simple, puisque  D  est diagonale et chaque élément diagonal est juste élevé à la puissance  n .

2. Compréhension et analyse des systèmes dynamiques
    La diagonalisation aide à comprendre le comportement à long terme des systèmes dynamiques linéaires. 
    Par exemple, dans l’étude des systèmes différentielles ou des chaînes de Markov, connaître la diagonalisation permet de prévoir comment un système évolue au fil du temps.

3. Applications dans la résolution d’équations différentielles

    La diagonalisation est utile pour résoudre des systèmes d’équations différentielles linéaires. 
    En diagonalissant la matrice associée, on peut décomposer le système en équations plus simples à résoudre.

4. Transformation linéaire simplifiée

    Dans le contexte de la géométrie, diagonaliser une matrice permet de comprendre et de simplifier la transformation linéaire qu’elle représente, car la matrice diagonale indique directement les valeurs propres qui définissent l’étirement ou la compression dans les directions propres.

5. Décomposition spectrale

    La diagonalisation est liée à la décomposition spectrale, qui permet de décomposer une matrice en une somme de matrices pondérées par leurs valeurs propres. 
    Cela a des applications dans la mécanique quantique, la vibration des structures, l’analyse des graphes, et la compression de données (comme l’analyse en composantes principales).
    
##### Etapes pour diagonaliser une matrice :

0. Pour toute matrice A
1. Calcul des valeurs propres (eighenValues)
2. Calcul des vecteurs propres (eighenVectors ou matrice P), c'est la construction de la matrice de passage P tel que → Chaque colonne de P est un vecteur propre de A 
3. Verifier l'independance lineaire des vecteurs propres, revient à verifier que la matrice P formé par ces vecteurs est inversible. La mtrice est inversible si son detertmiannt est non nul (det_P ≠ 0) 
4. Construction de la matrice diagonale D tel que → La matrice D a pour valeur diagonle les valeurs propres de A placées dans le meme ordre que les vecteurs propres de P
5. Calcul de l'inverse de P → P-1
6. Verifier l'equation  A = PDP^{-1}

In [16]:
matrix = np.array([[2, 1, 1], 
                   [1, 3, 1], 
                   [1, 1, 4]])

identityMatrix = np.identity(3) # Matrice identité 3x3

print("_______Diagonalisation d'une matrice 3x3______________")
print("0 : Matrice : ")
print(matrix)
print("______________________________________________________")
# 1 Calcul des valeurs propres
print("1 : Valeurs propres : ")
eigenValues = np.linalg.eigvals(matrix)
print(eigenValues)
print("______________________________________________________")
# 2 Calcul des vecteurs propres
print("2 : Vecteurs propres : ")
eigenVectors = np.linalg.eig(matrix)[1]
print(eigenVectors)
print("______________________________________________________")

#3 verification de l'independance des vecteurs propres
print("3 : Verification de l'independance des vecteurs propres : ")

# on calcule le determinant de la matrice vecteurs propres
det_P = np.linalg.det(eigenVectors)

if det_P != 0:
    print("Les vecteurs propres sont independants")
else:
    print("Les vecteurs propres ne sont pas independants, la matrice n'est pas diagonalisable")
    pass 

print("______________________________________________________")
print("4 : Construction de la matrice de passage P : ")
# on cherche la matrice inverse de la matrice des vecteurs propres
inverse = np.linalg.inv(eigenVectors)
print(inverse)
print("______________________________________________________")
print("5 : Construction de la matrice diagonale : ")
# on construit la matrice diagonale
diagonal = np.diag(eigenValues)
print(diagonal)

print("______________________________________________________")
# on calcule l'inverse de la matrice des vecteurs propres
print ("6 : Inverse de la matrice des vecteurs propres : ")
inverse = np.linalg.inv(eigenVectors)
print(inverse)
print("______________________________________________________")

print("7 : Verification de la diagonalisation de la matrice : ")
# on verifie que la matrice est bien diagonalisable
result = eigenVectors @ diagonal @ inverse
print(result)
print("______________________________________________________")


_______Diagonalisation d'une matrice 3x3______________
0 : Matrice : 
[[2 1 1]
 [1 3 1]
 [1 1 4]]
______________________________________________________
1 : Valeurs propres : 
[5.21431974 1.32486913 2.46081113]
______________________________________________________
2 : Vecteurs propres : 
[[ 0.39711255  0.88765034 -0.23319198]
 [ 0.52065737 -0.42713229 -0.73923874]
 [ 0.75578934 -0.17214786  0.63178128]]
______________________________________________________
3 : Verification de l'independance des vecteurs propres : 
Les vecteurs propres sont independants
______________________________________________________
4 : Construction de la matrice de passage P : 
[[ 0.39711255  0.52065737  0.75578934]
 [ 0.88765034 -0.42713229 -0.17214786]
 [-0.23319198 -0.73923874  0.63178128]]
______________________________________________________
5 : Construction de la matrice diagonale : 
[[5.21431974 0.         0.        ]
 [0.         1.32486913 0.        ]
 [0.         0.         2.46081113]]
___________

In [17]:
# Verifications avec les fonctions python
print("Diagonale avec function python : ")
diagonal = np.diag(matrix)
print(diagonal)
print("______________________________________________________")


Diagonale avec function python : 
[2 3 4]
______________________________________________________


## 2. Géométrie
### 2.1. Géométrie Plane
- Propriétés des triangles
- Propriétés des quadrilatères
- Cercles et angles

### 2.2. Géométrie dans l'Espace
- Solides et volumes
- Coordonnées dans l'espace
- Vecteurs et produits scalaires

## 3. Analyse
### 3.1. Dérivées
- Définition
- Règles de dérivation
- Applications des dérivées

### 3.2. Intégrales
- Définition et interprétation
- Techniques d'intégration
- Applications des intégrales

## 4. Probabilités et Statistiques
### 4.1. Probabilités
- Concepts de base
- Lois de probabilité
- Variables aléatoires

### 4.2. Statistiques descriptive
- Analyse des données
- Mesures de tendance centrale
- Mesures de dispersion
- Ecart type : standard deviation
- Notion de quartil
- A/B test
- Distribution (Normal curve)
- Intervalle de confiance



## 5. Logique et Raisonnement
- Logique propositionnelle
- Raisonnement déductif et inductif
- Preuves mathématiques

## 6. Ressources Supplémentaires
- Livres recommandés
- Sites web et vidéos éducatives
- Applications et outils en ligne